# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

semplice = env.Clone()

loader_sources= []
stage2_sources = []

loader_sources = SConscript('mbr/SConscript')
stage2_sources = SConscript('stage2/SConscript')

semplice.Object('../obj/semplice/loader', loader_sources)
semplice.Object('../obj/semplice/stage2', stage2_sources)
