# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

sources = []
loader_sources= []
stage2_sources = []

semplice = env.Clone()

Export('sources', 'semplice')
Export('loader_sources', 'semplice')
Export('stage2_sources', 'semplice')

SConscript('mbr/SConscript')
SConscript('stage2/SConscript')

#distreq += ['src/metodo.exe']

#semplice.Program('semplice', sources)

semplice.Object('../obj/semplice/loader', loader_sources)
semplice.Object('../obj/semplice/stage2', stage2_sources)
